/**
 * Constantes conceituais do Motor Bancário (MBC-01).
 * Sem persistência. Sem Open Finance.
 * @module motores/bancario/contracts/constantes
 */
'use strict';

const DIRECAO = Object.freeze({
  ENTRADA: 'entrada',
  SAIDA: 'saida',
  TRANSFERENCIA: 'transferencia'
});

const STATUS_CONCILIACAO = Object.freeze({
  PENDENTE: 'pendente',
  CONCILIADA: 'conciliada',
  IGNORADA: 'ignorada',
  DIVERGENTE: 'divergente'
});

const ORIGEM_TRANSACAO = Object.freeze({
  MANUAL: 'manual',
  PROVIDER: 'provider',
  OPEN_FINANCE: 'open_finance',
  OFX: 'ofx'
});

const NATUREZA_TRANSFERENCIA = Object.freeze({
  INTERNA: 'interna',
  INTEREMPRESA: 'interempresa'
});

const SALDO = Object.freeze({
  INFORMADO_BANCO: 'informado_banco',
  CALCULADO_SISTEMA: 'calculado_sistema'
});

const TIPOS_CONTA = Object.freeze(['CORRENTE', 'POUPANCA', 'PAGAMENTO', 'OUTRA']);

const TIPOS_TRANSACAO = Object.freeze([
  'PIX', 'TED', 'DOC', 'BOLETO', 'CARTAO', 'TARIFA',
  'TRANSFERENCIA', 'DEPOSITO', 'SAQUE', 'OUTROS'
]);

const STATUS_REGISTRO = Object.freeze({
  CRIADA: 'CRIADA',
  JA_EXISTENTE: 'JA_EXISTENTE'
});

const ORIGEM_FINANCEIRA = Object.freeze({
  FINANCEIRO: 'FINANCEIRO',
  CONTAS_RECEBER: 'CONTAS_RECEBER',
  CONTAS_RECEBER_PAGAMENTO: 'CONTAS_RECEBER_PAGAMENTO'
});

const CODIGO_PROVIDER = Object.freeze({
  MOCK: 'MOCK',
  MOCK_OPEN_FINANCE: 'MOCK_OPEN_FINANCE',
  OPEN_FINANCE_REAL: 'OPEN_FINANCE_REAL'
});

const ESCOPOS_OPEN_FINANCE = Object.freeze(['CONTAS', 'SALDOS', 'TRANSACOES']);

const STATUS_CONSENTIMENTO = Object.freeze({
  INICIADO: 'INICIADO',
  AGUARDANDO_AUTORIZACAO: 'AGUARDANDO_AUTORIZACAO',
  AUTORIZADO: 'AUTORIZADO',
  EXPIRADO: 'EXPIRADO',
  REVOGADO: 'REVOGADO',
  NEGADO: 'NEGADO',
  ERRO: 'ERRO'
});

const CONSENTIMENTOS_OPERACIONAIS = Object.freeze([
  'INICIADO',
  'AGUARDANDO_AUTORIZACAO',
  'AUTORIZADO'
]);

const STATUS_SINCRONIZACAO = Object.freeze({
  PENDENTE: 'PENDENTE',
  SINCRONIZANDO: 'SINCRONIZANDO',
  SUCESSO: 'SUCESSO',
  ERRO: 'ERRO',
  CONSENTIMENTO_EXPIRADO: 'CONSENTIMENTO_EXPIRADO',
  CONSENTIMENTO_REVOGADO: 'CONSENTIMENTO_REVOGADO'
});

const AMBIENTE_INTEGRACAO = Object.freeze({
  TESTE: 'TESTE',
  SANDBOX: 'SANDBOX',
  HOMOLOGACAO: 'HOMOLOGACAO',
  PRODUCAO: 'PRODUCAO'
});

const ERROS = Object.freeze({
  EMPRESA_OBRIGATORIA: 'MBC_EMPRESA_OBRIGATORIA',
  NAO_IMPLEMENTADO: 'MBC_NAO_IMPLEMENTADO',
  SINCRONIZACAO_FORA_ESCOPO: 'MBC_SINCRONIZACAO_FORA_ESCOPO',
  CONCILIACAO_FORA_ESCOPO: 'MBC_CONCILIACAO_FORA_ESCOPO',
  DTO_INVALIDO: 'MBC_DTO_INVALIDO',
  IDEMPOTENCIA_INCOMPLETA: 'MBC_IDEMPOTENCIA_INCOMPLETA',
  INSTITUICAO_NAO_ENCONTRADA: 'MBC_INSTITUICAO_NAO_ENCONTRADA',
  INSTITUICAO_INATIVA: 'MBC_INSTITUICAO_INATIVA',
  CONTA_NAO_ENCONTRADA: 'MBC_CONTA_NAO_ENCONTRADA',
  TIPO_INVALIDO: 'MBC_TIPO_INVALIDO',
  CODIGO_DUPLICADO: 'MBC_CODIGO_DUPLICADO',
  NOME_OBRIGATORIO: 'MBC_NOME_OBRIGATORIO',
  NUMERO_OBRIGATORIO: 'MBC_NUMERO_OBRIGATORIO',
  CONFLITO_EXCLUSAO: 'MBC_CONFLITO_EXCLUSAO',
  CONTA_INATIVA_PRINCIPAL: 'MBC_CONTA_INATIVA_PRINCIPAL',
  CONTA_INATIVA: 'MBC_CONTA_INATIVA',
  VALOR_INVALIDO: 'MBC_VALOR_INVALIDO',
  DIRECAO_INVALIDA: 'MBC_DIRECAO_INVALIDA',
  DATA_INVALIDA: 'MBC_DATA_INVALIDA',
  PERIODO_INVALIDO: 'MBC_PERIODO_INVALIDO',
  TRANSACAO_NAO_ENCONTRADA: 'MBC_TRANSACAO_NAO_ENCONTRADA',
  TIPO_TRANSACAO_INVALIDO: 'MBC_TIPO_TRANSACAO_INVALIDO',
  EMPRESA_CONTA_DIVERGENTE: 'MBC_EMPRESA_CONTA_DIVERGENTE',
  SOURCE_OBRIGATORIO: 'MBC_SOURCE_OBRIGATORIO',
  CONCILIACAO_NAO_ENCONTRADA: 'MBC_CONCILIACAO_NAO_ENCONTRADA',
  JA_CONCILIADA: 'MBC_JA_CONCILIADA',
  REGISTRO_FINANCEIRO_NAO_ENCONTRADO: 'MBC_REGISTRO_FINANCEIRO_NAO_ENCONTRADO',
  ORIGEM_INVALIDA: 'MBC_ORIGEM_INVALIDA',
  VALORES_INCOMPATIVEIS: 'MBC_VALORES_INCOMPATIVEIS',
  COMPATIBILIDADE_FINANCEIRA: 'MBC_COMPATIBILIDADE_FINANCEIRA',
  OBSERVACAO_OBRIGATORIA: 'MBC_OBSERVACAO_OBRIGATORIA',
  CONCILIACAO_INATIVA: 'MBC_CONCILIACAO_INATIVA',
  PROVIDER_DESCONHECIDO: 'MBC_PROVIDER_DESCONHECIDO',
  AMBIENTE_INVALIDO: 'MBC_AMBIENTE_INVALIDO',
  CONFIG_NAO_ENCONTRADA: 'MBC_CONFIG_NAO_ENCONTRADA',
  CONFIG_INATIVA: 'MBC_CONFIG_INATIVA',
  SECRET_KEY_AUSENTE: 'MBC_SECRET_KEY_AUSENTE',
  PROVIDER_NAO_EXECUTAVEL: 'MBC_PROVIDER_NAO_EXECUTAVEL',
  CONSENTIMENTO_NAO_ENCONTRADO: 'MBC_CONSENTIMENTO_NAO_ENCONTRADO',
  CONSENTIMENTO_INVALIDO: 'MBC_CONSENTIMENTO_INVALIDO',
  AUTORIZACAO_INVALIDA: 'MBC_AUTORIZACAO_INVALIDA',
  INSTITUICAO_INCOMPATIVEL: 'MBC_INSTITUICAO_INCOMPATIVEL',
  ESCOPO_INVALIDO: 'MBC_ESCOPO_INVALIDO',
  CONSENTIMENTO_JA_OPERACIONAL: 'MBC_CONSENTIMENTO_JA_OPERACIONAL',
  SINCRONIZACAO_EM_ANDAMENTO: 'MBC_SINCRONIZACAO_EM_ANDAMENTO',
  PROVIDER_SEM_SINCRONIZACAO: 'MBC_PROVIDER_SEM_SINCRONIZACAO',
  SUGESTAO_NAO_ENCONTRADA: 'MBC_SUGESTAO_NAO_ENCONTRADA',
  SUGESTAO_INVALIDA: 'MBC_SUGESTAO_INVALIDA',
  MATCHING_CONFLITO: 'MBC_MATCHING_CONFLITO',
  PROVIDER_TIMEOUT: 'MBC_PROVIDER_TIMEOUT',
  PROVIDER_RATE_LIMIT: 'MBC_PROVIDER_RATE_LIMIT',
  PROVIDER_INDISPONIVEL: 'MBC_PROVIDER_INDISPONIVEL',
  CURSOR_INVALIDO: 'MBC_CURSOR_INVALIDO'
});

const CATEGORIA_ERRO_PROVIDER = Object.freeze({
  AUTENTICACAO: 'AUTENTICACAO',
  AUTORIZACAO: 'AUTORIZACAO',
  CONSENTIMENTO: 'CONSENTIMENTO',
  TIMEOUT: 'TIMEOUT',
  RATE_LIMIT: 'RATE_LIMIT',
  INDISPONIBILIDADE: 'INDISPONIBILIDADE',
  DADOS_INVALIDOS: 'DADOS_INVALIDOS',
  PAGINACAO: 'PAGINACAO',
  CURSOR_INVALIDO: 'CURSOR_INVALIDO',
  ERRO_INTERNO: 'ERRO_INTERNO'
});

function classificarErroProvider(err) {
  if (!err) return CATEGORIA_ERRO_PROVIDER.ERRO_INTERNO;
  if (err.categoria && CATEGORIA_ERRO_PROVIDER[err.categoria]) return err.categoria;
  const code = String(err.code || '');
  const msg = String(err.message || '').toLowerCase();
  if (code === ERROS.SECRET_KEY_AUSENTE) return CATEGORIA_ERRO_PROVIDER.AUTENTICACAO;
  if (code === ERROS.AUTORIZACAO_INVALIDA) return CATEGORIA_ERRO_PROVIDER.AUTORIZACAO;
  if (code === ERROS.PROVIDER_DESCONHECIDO || code === ERROS.PROVIDER_NAO_EXECUTAVEL) {
    return CATEGORIA_ERRO_PROVIDER.AUTORIZACAO;
  }
  if (
    code === ERROS.CONSENTIMENTO_NAO_ENCONTRADO
    || code === ERROS.CONSENTIMENTO_INVALIDO
    || code === ERROS.CONSENTIMENTO_JA_OPERACIONAL
  ) {
    return CATEGORIA_ERRO_PROVIDER.CONSENTIMENTO;
  }
  if (code === ERROS.PROVIDER_TIMEOUT || /timeout|timed out|etimedout/.test(msg)) {
    return CATEGORIA_ERRO_PROVIDER.TIMEOUT;
  }
  if (code === ERROS.PROVIDER_RATE_LIMIT || /rate.?limit|429/.test(msg)) {
    return CATEGORIA_ERRO_PROVIDER.RATE_LIMIT;
  }
  if (code === ERROS.CURSOR_INVALIDO) return CATEGORIA_ERRO_PROVIDER.CURSOR_INVALIDO;
  if (code === ERROS.DTO_INVALIDO || code === ERROS.VALOR_INVALIDO) {
    return CATEGORIA_ERRO_PROVIDER.DADOS_INVALIDOS;
  }
  if (code === ERROS.PROVIDER_INDISPONIVEL || err.statusCode === 502 || err.statusCode === 503) {
    return CATEGORIA_ERRO_PROVIDER.INDISPONIBILIDADE;
  }
  if (/pagina|paginação|paginacao/.test(msg)) return CATEGORIA_ERRO_PROVIDER.PAGINACAO;
  return CATEGORIA_ERRO_PROVIDER.ERRO_INTERNO;
}

function erroMbc(code, message, statusCode = 400) {
  const err = new Error(message);
  err.code = code;
  err.statusCode = statusCode;
  return err;
}

module.exports = {
  DIRECAO,
  STATUS_CONCILIACAO,
  ORIGEM_TRANSACAO,
  NATUREZA_TRANSFERENCIA,
  SALDO,
  TIPOS_CONTA,
  TIPOS_TRANSACAO,
  STATUS_REGISTRO,
  ORIGEM_FINANCEIRA,
  CODIGO_PROVIDER,
  AMBIENTE_INTEGRACAO,
  ESCOPOS_OPEN_FINANCE,
  STATUS_CONSENTIMENTO,
  CONSENTIMENTOS_OPERACIONAIS,
  STATUS_SINCRONIZACAO,
  CATEGORIA_ERRO_PROVIDER,
  ERROS,
  erroMbc,
  classificarErroProvider
};
